### ISSUE TITLE
Convert the days to years/weeks/days into "years/months/weeks/days"

### ISSUE THREAD

**Issue by AmruthaSri852** [Hrjha30/C-Programming-Language#3]
1. for a long amount of days just a week are not enough... So, Where is the month? take it input days/30 and proceed
2. Try to add C++ to this; if you already did, ignore this!
3. I ran the code input days as 23 and the output is 3 weeks and 2 days then I got it to strike to convert mins, sec, and hours.
4. Later I gave input days as 365 and hope you know what happens; acknowledge that.

**Comment by Hrjha30** [comment]
1. You are correct but I didn't want to add months so didn't add.
2. I will add in C++ also.
